spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: admin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect

  sql:
    init:
      mode: never

server:
  port: 8080

logging:
  level:
    root: INFO
    com.springnews.api: DEBUG
    com.springnews.service: DEBUG
    com.springnews.repository: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/springnews.log
